spring:
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;MODE=Oracle
      username: sa
      password: sa
  jpa:
     hibernate:
      show-sql: true
      
eureka:
  client:
    service-url:
            defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
