spring:
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
     hibernate:
      show-sql: false
      
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
