spring:
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  jpa:
     hibernate:
      show-sql: false
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1